- index.html
- package-lock.json
- package.json
- src/App.jsx
- src/components/NavBar.jsx
- src/index.css
- src/pages/Home.jsx
- tailwind.config.js
- Included MUI and Tailwind CSS. For now the intention is to prioritise these frameworks over Bootstrap, but feel free to work with Bootstrap as long as you are still unfamiliar with these.
- Created a basic NavBar components. Routes still need to be added.
> Basic NavBar and MUI/Tailwind

- src/components/NavBar.jsx
replaces the a-tag hrefs with React Links
> Add Links to Navbar instead of href anchors

- src/App.jsx
- src/components/CreateItemForm.jsx
- src/pages/CreateItemPage.jsx
This PR adds a new page for creating an item in the inventory of the association. A new route /create-item has been added to the application, which renders a CreateItemPage component. This component contains the CreateItemForm component, which is used to create a new item.
The CreateItemForm component consists of a form that takes in two inputs, name and description. The form is submitted when the user clicks the "Create Item" button. Upon form submission, the handleSubmit function sends a POST request to the /items API endpoint with the data from the form. If the item is successfully created, the user is redirected to the ItemsPage.
Changes Made
- Added a new route /create-item to the application.
- Created CreateItemPage component to render the form for creating a new item.
- Created …
> Create Item Routes/Component/Page

- index.html
- package-lock.json
- package.json
- postcss.config.js
- src/App.css
- src/App.jsx
- src/components/NavBar.jsx
- src/index.css
- src/pages/Home.jsx
- tailwind.config.js
Not the final design, but some basic stylings to make the dev phase a little more pleasant.
NavBar polished and responsive for now. Search bar should be added in a separate branch because it's a bigger challenge.
> Home basic layout

- src/pages/SignupPage.jsx
Add image file upload via Cloudinary
I'll post the .env secrets in the chat
> Add image upload

- src/App.css
- src/components/NavBar.jsx
- src/components/Profile/ProfileBio.jsx
- src/components/Profile/ProfilePicture.jsx
- src/pages/ProfilePage.jsx
Basic layout is done.
I'm impressed that this is already responsive and optimised for mobile too. I thought the absolute off-set of the profile picture was going to make me struggle. Was so much easier than with just Bootstrap.
> Further profile page improvements

- src/pages/ProfilePage.jsx
The text that said "you havent set any categories yet" didn't show bc we had set the condition of "object doesnt exist" - but the array exists when the user is loaded; we should ask if the length of the array is 0.
But since the array doesn't exists on a first page render (the user gets fetched upon the first useEffect hook using an axios request), the whole thing breaks down completely. I now wrapped it in a condition that asks if the currentUser.categories are even a thing, and then the whole page gets rendered
> Add category exists condition

- src/App.jsx
- src/components/Collections/CollectionCard.jsx
- src/components/Collections/CreateCollectionForm.jsx
- src/components/ImageUploader.jsx
- src/pages/CollectionPages/MyCollection.jsx
Image upload and redirection after creating collection to this collection now works.
> Image upload for collections

- src/pages/ProfilePage.jsx
I added the condition to check for categories/collections in the user profile.
We first needed to check if the array objects were there, and only if they're there we can check their length. If its 0, we get a "u have no interests" message
> Add condition to show categories/collections

- src/App.jsx
- src/pages/CollectionPages/EditCollection.jsx
- src/pages/CollectionPages/MyCollection.jsx
- src/services/getCollection.js
Edit collection now works, it will pre-populate the name and description and won't touch the uplloaded image if you don't change it
> Create edit collection component

- src/App.css
- src/App.jsx
- src/components/Collections/CollectionHeader.jsx
- src/components/Footer.jsx
- src/components/NavBar.jsx
- src/components/Profile/ProfileHeader.jsx
- src/pages/CollectionPages/CreateCollectionPage.jsx
- src/pages/CollectionPages/MyCollection.jsx
- src/pages/CreateItemPage.jsx
- src/pages/Home.jsx
- src/pages/ProfilePage.jsx
Basic style improvements and a basic footer. To be improved as we add more functions.
> Home view foundation

- src/App.css
- src/components/Collections/AllCollections.jsx
- src/pages/Home.jsx
- src/pages/ProfilePage.jsx
Hey guys,
so I made this **popular Collections** section on Home.
**To make this work**, please run the seed-collections.js, they contain new collections with valid likes (consisting of arrays of valid userId's). It is advisable to also delete your old collections. If you don't, you MIGHT get some errors.
Note: I broke the Welcome Back {user.username} thingy, **I'm sorry Nana!!** Would be nice if somebody could fix this before merging. 
Gomen nasai watashi no baka mitai na koto ni tsuite, yoroshiku onegaishimasu!!
> Popular Collections in Home

- src/components/CreateForm.jsx
- src/pages/CollectionPages/EditCollection.jsx
- src/pages/ItemPages/CreateItemPage.jsx
- src/pages/ProfilePage.jsx
Just a small update to add basic styling to our new pages. Not final, but at least we shouldn't any pages with chaotic views anymore for now.
> Overall layout improvements

- src/components/CreateForm.jsx
- src/components/Items/ItemCard.jsx
- src/components/SelectCategories.jsx
- src/pages/CollectionPages/EditCollection.jsx
- src/pages/CollectionPages/MyCollection.jsx
- src/pages/ItemPages/EditItem.jsx
- src/pages/ItemPages/MyItem.jsx
Since everybody can view all collections (right now) and popular collections later, I included a check function that compares the collections creator ID with the current User ID to see if the user should be allowed to alter the collection in any way
> Protect collection to be edited from other users

- src/App.jsx
- src/components/Collections/CollectionCard.jsx
- src/components/CreateForm.jsx
- src/components/CreateItemForm.jsx
- src/components/Items/ItemCard.jsx
- src/pages/CollectionPages/EditCollection.jsx
- src/pages/CollectionPages/MyCollection.jsx
- src/pages/ItemPages/CreateFreeItemPage.jsx
- src/pages/ItemPages/EditItem.jsx
- src/pages/ProfilePage.jsx
We can now create Items that are not associated with collections
> Create standalone item

- src/components/Profile/CategoryTags.jsx
- src/components/Profile/ProfileBio.jsx
this is just the finishing touch of what Nana built with displaying Tags in the user profile
> Finish displaying tags in user profile

- src/components/Profile/ProfileBio.jsx
- src/pages/ProfilePage.jsx
- User profiles now display either a follow/unfollow button or an edit profile button depending on who's visiting whose profile
- Add collection button is also hidden if the logged in user is not authorised to do so.
- Can't really test if the unfollow button is showing up right now because follow/unfollow routes don't exist yet. But syntax looks correct to me.
> User profile authorisation

- src/App.jsx
- src/pages/ProfilePage.jsx
- src/pages/User/ChangePasswordPage.jsx
- src/pages/User/DeleteUserPage.jsx
- src/pages/User/EditProfilePage.jsx
It is done and now it also works to change your password and delete your account!
> Delete user & change password functionalities

- src/components/NavBar.jsx
The trick was to have the "Link" component wrap the whole ListItem in order to trigger the link from the whole List area
> Whole button in sidebar will trigger links

- src/components/ImageUploader/HeaderImageUploader.jsx
- src/components/ImageUploader/ImageUploader.jsx
- src/components/Items/AddItemToCollection.jsx
- src/pages/Home.jsx
- src/pages/ProfilePage.jsx
- src/pages/User/ChangePasswordPage.jsx
- src/pages/User/DeleteUserPage.jsx
- src/pages/User/EditProfilePage.jsx
Found some more "const API_URL" declarations and replaced them with imports of the apiConfig file
I hope that the deploy works :D
> Import API URL instead of declaring it

- src/components/CreateForm.jsx
- src/pages/ItemPages/EditItem.jsx
Doesnt delete the comment yet...but we can merge what I fixed so far
> Fix  delete comment from item if user deletes item from collection / push comments into User and Items

- src/components/CreateForm.jsx
- src/components/Items/AddItemToCollection.jsx
- src/pages/ItemPages/EditItem.jsx
- src/pages/ItemPages/MyItem.jsx
Okay a million things are happening here,
we can now write comments on Items we create
we can write comments on other peoples items (need to put in the fail safe that we HAVE to use the item in our collection first)
we can only ever change the comment we already wrote
My brain hurts, frontend edition
> Fix things to do with item adding and deleting

- .gitignore
- src/App.jsx
- src/components/Profile/UserStatistics.jsx
- src/pages/User/Followers.jsx
- src/pages/User/PeopleIFollow.jsx
The pages now work!
We should definitely move the "following" page to the sidebar, since it's private and a user can see the users theyre following.
> People i follow page

- src/App.css
- src/components/Items/CreateItemForm.jsx
- src/components/Items/ItemCard.jsx
- src/components/Profile/UserCard.jsx
- src/components/Profile/UserStatistics.jsx
- src/pages/CollectionPages/MyCollection.jsx
- src/pages/ItemPages/CreateItemPage.jsx
- src/pages/ItemPages/EditItem.jsx
- src/pages/ItemPages/MyItem.jsx
- src/pages/SearchResults.jsx
- src/pages/User/BookmarksPage.jsx
- src/pages/User/EditProfilePage.jsx
This PR includes basic styling of all pages that were "blown out of propotion" due to lack of proper containers and sectioning.
- Bookmarks
- SearchResults
- MyItem
- MyCollection
- EditItem
ItemCard was updated a little, and a new basic UserCard is being rendered in SearchResults now.
I've not changed any functionalities at all. I especially left the EditItem form unchanged because it's still a big work in progress, all I did was add the containers around it.
The styling is not final, but each individual page will take me much longer to get to the final look. For now, I think it's good that we can work with a cleaner look throughout the entire app.
> UI update part 2

- src/components/Collections/PopularCollections.jsx
- src/components/Collections/RecommendedCollections.jsx
- src/context/auth.context.jsx
- src/main.jsx
- src/pages/Home.jsx
- src/pages/ProfilePage.jsx
> Recommended collections

- src/App.jsx
- src/components/Profile/UserStatistics.jsx
- src/pages/User/Followers.jsx
This is a fix so that the "Followers" page actually shows up
> Fix /followers page to show stuff

- src/components/Items/AllItems.jsx
- src/components/Items/RecommendedItems.jsx
- src/components/Items/TrendingItems.jsx
- src/pages/Home.jsx
If you want to test this, there is a script published on the server.
> Trending Items and Recommended Items working

- src/components/Collections/CollectionCard.jsx
- src/pages/ItemPages/EditItem.jsx
- src/pages/ItemPages/MyItem.jsx
When we have an item in a collection, and click on that item, we get to the details page - I got it done that the collections ID will also be found on that item page (by comparing all of the users collections and all of the items collections).
Only when there is a match (and the item is in a colelction and that collection is in the users array of collections) is the user allowed to even enter the Edit Form.
Once there, there is a check between the currentUsers ID and the ID of this item's creator. If we have a match, you get to see the whole form for editing. if not, you only see the form for commenting and altering your comment.
> Update for editing and deleting items

- src/components/Items/CreateItemSearch.jsx
In the Item search when adding an item to a collection, and you choose an existing item, you can now succesfully leave a comment using the pop-up modal.
To be clear, I only added the commenting functionality - the behemoth of complex code was all Nana!
> Add a comment using the add item modal

- src/components/Bookmarks/BookmarkButton.jsx
- src/components/Likes/LikeButton.jsx
- src/pages/CollectionPages/MyCollection.jsx
- src/pages/ItemPages/MyItem.jsx
The like button now works I think!
> Like button in collections and items

- package-lock.json
- package.json
- src/components/Collections/AllCollections.jsx
- src/components/Collections/RecommendedCollections.jsx
- src/components/Items/AllItems.jsx
- src/components/Items/CreateItemForm.jsx
- src/components/Items/RecommendedItems.jsx
> Openai descriptions

- src/components/NavBar.jsx
I mean, that was just inserting a link
> add working page link

- src/App.jsx
- src/components/Items/ItemCard.jsx
- src/components/NavBar.jsx
- src/pages/User/BookmarksPage.jsx
- src/pages/User/MyLikesPage.jsx
- src/services/apiConfig.js
Almost the same as the bookmarks page with a new MUI icon
> Create mylikes page

- src/pages/ProfilePage.jsx
Now, when you try to access a name in the URL that doesnt exist, the webpage will tell you so.
> Update to show "user doesnt exist" message

- src/components/Items/CreateItemForm.jsx
- src/components/Items/CreateItemSearch.jsx
- src/pages/ItemPages/MyItem.jsx
If we now create items using the "add items" button from our own collection, the created item will be pushed directly into that collection.
You still have the opportunity to add the item to another one of your collections, but it for sure now will already be present in the collection to which you wanted to add it in the first place.
> Push newly created add items directly to collection

- src/components/Items/AddItemToCollection.jsx
- src/components/Items/CreateItemForm.jsx
- src/components/Items/CreateItemSearch.jsx
- src/pages/ItemPages/MyItem.jsx
This conditional render just works in the way that it checks if the current item is in EVERY other collection of a user.
If so, you won't get the prompt to add it to another collection.
If you make a new collection or delete the item from one collection, you get the prompt again.
> Condition to add item

- src/components/Collections/CollectionInfo.jsx
- src/components/Profile/CategoryTags.jsx
- src/components/Profile/ProfileBio.jsx
Category tags in MyCollection and ProfilePage should display correctly now on all viewports.
> Category tags linebreak fix

- package-lock.json
- package.json
- src/components/Collections/AllCollections.jsx
- src/components/Items/AllItems.jsx
- src/components/Items/CreateItemForm.jsx
- src/components/Items/CreateItemSearch.jsx
- src/components/NavBar.jsx
- src/components/RouteProtectors/IsPrivate.jsx
- src/components/RouteProtectors/IsPublic.jsx
- src/pages/CollectionPages/MyCollection.jsx
- src/pages/ProfilePage.jsx
- src/pages/SearchResults.jsx
Loading spinners were added for the most important components:
- AllItems.jsx
- AllCollections.jsx
- replaced "Loading ..." on isPrvate and isPublic with spinners
- SearchResults.jsx
Included some conditional rendering when no results are returned after an initial search (or if no interests were specified which won't show anything for home page recommendations).
This doesn't cover every single component that makes API calls or has other significant loading times, but these are the most noticeable ones. I'll probably add more as I continue styling the remaining pages.
I also hid the links in the sidebar that we're not using at the moment (Messages, Notifications, etc.)
> Loading spinners

- src/components/Items/CreateItemForm.jsx
Creating a description and submitting the create item form are now separated concerns
> Add a "create description" button

- src/App.jsx
Added the "isPrivate" route protector to those routes not accessible from the public
> Secure routes

- src/App.jsx
- src/components/Collections/CollectionCard.jsx
- src/components/Collections/RecommendedCollections.jsx
- src/components/DynamicSearch/SearchBar.jsx
- src/components/ImageUploader/HeaderImageUploader.jsx
- src/components/ImageUploader/ImageUploader.jsx
- src/components/Items/AddItemToCollection.jsx
- src/components/Items/CreateItemSearch.jsx
- src/components/Items/RecommendedItems.jsx
- src/components/Likes/LikeButton.jsx
- src/components/Profile/ProfileBio.jsx
- src/components/SelectCategories.jsx
- src/components/UserLogin/Login.jsx
- src/pages/CollectionPages/EditCollection.jsx
- src/pages/ItemPages/EditItem.jsx
- src/pages/ItemPages/MyItem.jsx
- src/pages/User/BookmarksPage.jsx
- src/pages/User/LogPage.jsx
- src/pages/User/MyLikesPage.jsx
- src/pages/User/PeopleIFollow.jsx
Adds the token verification to the axios requests.
if this opens up to many merge conflicts, it's not a priority
> Add token verification to most axios requests
